config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/secret', to: 'pages#index', as: :secret
  get '/sign_up', to: 'users#new', as: :sign_up

  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# sorceror king
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :email, uniqueness: true,
                    email_format: { message: 'invalid email format' }

  class << self
    # the best solution?
    def current_users
      where("#{sorcery_config.last_activity_at_attribute_name} IS NOT NULL") \
      .where("#{sorcery_config.last_logout_at_attribute_name} IS NULL
        OR #{sorcery_config.last_activity_at_attribute_name} > #{sorcery_config.last_logout_at_attribute_name}") \
      .where("#{sorcery_config.last_activity_at_attribute_name} > ? ", sorcery_config.activity_timeout.seconds.ago.utc.to_s(:db))
    end
  end
end

app/controllers/application_controller.rb
# control them all
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception

  helper_method :current_users

  def not_authenticated
    flash[:waring] = 'You have to authenticate to access this page'
    redirect_to :log_in
  end

  private

  def current_users
    User.current_users
  end
end

app/controllers/pages_controller.rb
# pages
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reset_passwords_controller.rb
# stupid users
class ResetPasswordsController < ApplicationController
  skip_before_action :require_login

  def create
    @user = User.find_by(email: params[:email])
    @user.deliver_reset_password_instructions! if @user
    flash[:success] = 'Instructions have been sent'
    redirect_to log_in_path
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated && return if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      flash[:success] = 'Password was successfully changed'
      redirect_to log_in_path
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
# sessions needs in control too
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
  end

  def create
    if login(params[:email], params[:password], params[:remember_me])
      flash[:success] = 'Welcome back!'
      redirect_back_or_to root_path
    else
      flash[:error] = 'Something wrong with your credentials'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:sucess] = 'See you'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
# control your users
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:create, :new, :activate]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Welcome!'
      login(params[:user][:email], params[:user][:password])
      redirect_to root_path
    else
      render 'new'
    end
  end

  def activate
    @user = User.load_from_activation_token(params[:id])

    if @user
      @user.activate!
      flash[:success] = 'User was successfully activated'
      redirect_to log_in_path
    else
      flash[:warning] = 'Cannot activate this user'
      redirect_to root_path
    end
  end

  # not tested & mailer didn't exist
  def unlock
    @user = User.load_from_unlock_token(params[:token])
    @user.unlock!
    flash[:success] = 'Account was successfully unlocked'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magical</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Magical', root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li>
                <%= link_to 'Secret Page', secret_path %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Sign up', sign_up_path %>
              </li>
              <li>
                <%= link_to 'Log in', log_in_path %>
              </li>
            <% end %>
          </ul>
          <% if current_user %>
            <ul class="nav navbar-nav pull-right">
              <li>
                <span><%= current_user.name %></span>
              </li>
              <li>
                <%= link_to 'Log out', log_out_path, method: :delete %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>

      <%= render '/shared/current_users' %>

    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Authorized only</p>

app/views/reset_passwords/edit.html.erb
<h1>Choose new password</h1>

<%= form_for @user, url: reset_password_path(@token), method: :path do %>
  <%= render '/shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', requred: true %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', requred: true %>
  </div>

  <%= submit_tag 'Set password', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/reset_passwords/new.html.erb
<h1>Reset Password</h1>

<%= form_tag :reset_passwords, method: :post do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email, nil,  class: 'form-control', requred: true %>
  </div>

  <%= submit_tag 'Send me instructions', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/shared/_current_users.html.erb
<div class="col-sm-3 well well-sm">
  <h3>Currently active users</h3>
  <ul>
    <% current_users.each do |user| %>
      <li>
        <%= user.name %>
      </li>
    <% end %> 
  </ul>
</div>

app/views/users/new.html.erb
<h1>Registration</h1>
<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', requred: true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', requred: true %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', requred: true %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', requred: true %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>

<% end %>